### ISSUE TITLE
Resizable tables

### ISSUE THREAD

**Issue by matheusvellone** [PillFall/Figma-Database-Table#10]
Currently the tables have fixed width and a long table name is truncated with ellipsis.
![image](https://user-images.githubusercontent.com/5989971/168180031-f1e3b151-2486-4694-a532-adf260d08123.png)

It would be great if users could control the width to show full table name (or to truncate it)

**Comment by matheusvellone** [comment]
Could not find anything on docs about allowing it to be resizable 😢 https://www.figma.com/widget-docs/api/component-AutoLayout/

Also, none of the plugins available on Figma was resizable, which makes me think it's not possible right now 😕

**Comment by PillFall** [comment]
That's right 😢. I also notice that some Widgets have a selector for the size, maybe we could add some widths sizes for the widget.
