### ISSUE TITLE
Add support for long names

### ISSUE THREAD

**Issue by Nick390** [PillFall/Figma-Database-Table#20]
If I have a long name this is how it will lock like. Can you fix it @PillFall, please
![Screenshot_94](https://github.com/user-attachments/assets/a683a49d-4d20-4d66-bb18-a380b5f7f485)

**Comment by PillFall** [comment]
Hi, I do not know if you notice, there is a size selector for really long tables

![context menu](https://github.com/user-attachments/assets/7d272849-a985-422d-be18-5b57ed2e6f02)
![size selector](https://github.com/user-attachments/assets/cdf9266e-1ad6-429d-9fda-fda9b5637b52)
![huge table](https://github.com/user-attachments/assets/37b1faec-847a-461f-b523-2f84eaad60a7)

Probably you need to update the widget in the top left menu click:
![update](https://github.com/user-attachments/assets/2f25729c-b7b3-40fe-ad4c-99e0ed354622)

**Comment by PillFall** [comment]
The available sizes are defined here, the `option` (aka size) is in pixels:

https://github.com/PillFall/Figma-Database-Table/blob/8bd11b7c8513bd0a08d4fb6e99f0edf025e25aee/plugin-src/size.tsx#L1-L22

**Comment by Nick390** [comment]
Thanks 👍🏼
